/**
 * GovSphere — Built-in Workflow Templates (v0.8.1)
 *
 * 10 government workflow templates that can be used to seed or scaffold
 * new workflow definitions. `isSystem = true` marks them as read-only originals.
 */

export interface BuiltInStepDef {
  order: number;
  name: string;
  description: string;
  durationHours: number;
  allowDelegate: boolean;
  allowEscalate: boolean;
  requireComment: boolean;
  requireSign: boolean;
}

export interface BuiltInTemplate {
  slug: string;
  name: string;
  description: string;
  trigger:
    | "MANUAL"
    | "DOCUMENT_CREATED"
    | "DOCUMENT_PUBLISHED"
    | "EMPLOYEE_TRANSFERRED"
    | "BUDGET_SUBMITTED"
    | "CONTRACT_UPLOADED"
    | "CUSTOM";
  stepDefinitions: BuiltInStepDef[];
}

export const BUILT_IN_TEMPLATES: BuiltInTemplate[] = [
  {
    slug: "minister-speech-approval",
    name: "Approbation du Discours Ministériel",
    description:
      "Workflow de validation d'un discours officiel du ministre, du rédacteur jusqu'au bureau du Ministre.",
    trigger: "DOCUMENT_CREATED",
    stepDefinitions: [
      {
        order: 0,
        name: "Rédacteur",
        description: "Préparation et soumission du discours",
        durationHours: 48,
        allowDelegate: false,
        allowEscalate: false,
        requireComment: false,
        requireSign: false,
      },
      {
        order: 1,
        name: "Chef de Division",
        description: "Révision linguistique et contenu",
        durationHours: 24,
        allowDelegate: true,
        allowEscalate: true,
        requireComment: true,
        requireSign: false,
      },
      {
        order: 2,
        name: "Directeur",
        description: "Validation des orientations politiques",
        durationHours: 24,
        allowDelegate: true,
        allowEscalate: true,
        requireComment: true,
        requireSign: false,
      },
      {
        order: 3,
        name: "Secrétaire Général",
        description: "Approbation finale avant le Ministre",
        durationHours: 12,
        allowDelegate: false,
        allowEscalate: false,
        requireComment: true,
        requireSign: true,
      },
      {
        order: 4,
        name: "Bureau du Ministre",
        description: "Signature et validation définitive",
        durationHours: 12,
        allowDelegate: false,
        allowEscalate: false,
        requireComment: false,
        requireSign: true,
      },
    ],
  },
  {
    slug: "official-letter-approval",
    name: "Approbation de Lettre Officielle",
    description: "Circuit standard de validation des courriers officiels sortants.",
    trigger: "DOCUMENT_CREATED",
    stepDefinitions: [
      {
        order: 0,
        name: "Rédacteur",
        description: "Rédaction de la lettre",
        durationHours: 24,
        allowDelegate: false,
        allowEscalate: false,
        requireComment: false,
        requireSign: false,
      },
      {
        order: 1,
        name: "Chef de Division",
        description: "Vérification et corrections",
        durationHours: 24,
        allowDelegate: true,
        allowEscalate: false,
        requireComment: false,
        requireSign: false,
      },
      {
        order: 2,
        name: "Directeur",
        description: "Approbation du contenu",
        durationHours: 24,
        allowDelegate: true,
        allowEscalate: true,
        requireComment: false,
        requireSign: false,
      },
      {
        order: 3,
        name: "Signataire Autorisé",
        description: "Signature officielle",
        durationHours: 8,
        allowDelegate: false,
        allowEscalate: false,
        requireComment: false,
        requireSign: true,
      },
    ],
  },
  {
    slug: "cabinet-memo-approval",
    name: "Approbation Note de Cabinet",
    description: "Circuit de validation des notes de cabinet destinées au Conseil des Ministres.",
    trigger: "DOCUMENT_CREATED",
    stepDefinitions: [
      {
        order: 0,
        name: "Initiateur",
        description: "Rédaction de la note",
        durationHours: 72,
        allowDelegate: false,
        allowEscalate: false,
        requireComment: false,
        requireSign: false,
      },
      {
        order: 1,
        name: "Directeur de Cabinet",
        description: "Révision et enrichissement",
        durationHours: 48,
        allowDelegate: true,
        allowEscalate: true,
        requireComment: true,
        requireSign: false,
      },
      {
        order: 2,
        name: "Secrétaire Général du Gouvernement",
        description: "Conformité légale et protocole",
        durationHours: 48,
        allowDelegate: false,
        allowEscalate: false,
        requireComment: true,
        requireSign: true,
      },
      {
        order: 3,
        name: "Premier Ministre",
        description: "Approbation finale et signature",
        durationHours: 24,
        allowDelegate: false,
        allowEscalate: false,
        requireComment: false,
        requireSign: true,
      },
    ],
  },
  {
    slug: "policy-approval",
    name: "Approbation de Politique Publique",
    description: "Processus de validation d'une nouvelle politique ou directive nationale.",
    trigger: "MANUAL",
    stepDefinitions: [
      {
        order: 0,
        name: "Direction Technique",
        description: "Élaboration de la politique",
        durationHours: 168,
        allowDelegate: true,
        allowEscalate: false,
        requireComment: false,
        requireSign: false,
      },
      {
        order: 1,
        name: "Comité Consultatif",
        description: "Avis et recommandations",
        durationHours: 168,
        allowDelegate: true,
        allowEscalate: true,
        requireComment: true,
        requireSign: false,
      },
      {
        order: 2,
        name: "Secrétaire Général",
        description: "Cohérence avec la politique gouvernementale",
        durationHours: 72,
        allowDelegate: false,
        allowEscalate: false,
        requireComment: true,
        requireSign: false,
      },
      {
        order: 3,
        name: "Ministre",
        description: "Approbation politique et signature",
        durationHours: 72,
        allowDelegate: false,
        allowEscalate: false,
        requireComment: false,
        requireSign: true,
      },
      {
        order: 4,
        name: "Conseil des Ministres",
        description: "Adoption en Conseil",
        durationHours: 168,
        allowDelegate: false,
        allowEscalate: false,
        requireComment: true,
        requireSign: true,
      },
    ],
  },
  {
    slug: "budget-approval",
    name: "Approbation Budgétaire",
    description: "Circuit d'approbation des demandes budgétaires et engagements financiers.",
    trigger: "BUDGET_SUBMITTED",
    stepDefinitions: [
      {
        order: 0,
        name: "Responsable de Programme",
        description: "Soumission et justification",
        durationHours: 48,
        allowDelegate: false,
        allowEscalate: false,
        requireComment: true,
        requireSign: false,
      },
      {
        order: 1,
        name: "Contrôleur Financier",
        description: "Vérification budgétaire",
        durationHours: 48,
        allowDelegate: true,
        allowEscalate: true,
        requireComment: true,
        requireSign: false,
      },
      {
        order: 2,
        name: "Directeur Administratif",
        description: "Validation de la conformité",
        durationHours: 24,
        allowDelegate: true,
        allowEscalate: true,
        requireComment: true,
        requireSign: false,
      },
      {
        order: 3,
        name: "Secrétaire Général",
        description: "Autorisation finale",
        durationHours: 24,
        allowDelegate: false,
        allowEscalate: false,
        requireComment: false,
        requireSign: true,
      },
      {
        order: 4,
        name: "Ministre des Finances",
        description: "Visa du Ministre des Finances",
        durationHours: 72,
        allowDelegate: false,
        allowEscalate: false,
        requireComment: false,
        requireSign: true,
      },
    ],
  },
  {
    slug: "employment-approval",
    name: "Approbation de Recrutement",
    description: "Processus d'approbation des nouvelles nominations et recrutements.",
    trigger: "MANUAL",
    stepDefinitions: [
      {
        order: 0,
        name: "Direction des Ressources Humaines",
        description: "Dossier de recrutement",
        durationHours: 72,
        allowDelegate: true,
        allowEscalate: false,
        requireComment: false,
        requireSign: false,
      },
      {
        order: 1,
        name: "Directeur Général",
        description: "Approbation de la nomination",
        durationHours: 48,
        allowDelegate: false,
        allowEscalate: true,
        requireComment: true,
        requireSign: false,
      },
      {
        order: 2,
        name: "Secrétaire Général",
        description: "Conformité réglementaire",
        durationHours: 48,
        allowDelegate: false,
        allowEscalate: false,
        requireComment: true,
        requireSign: true,
      },
      {
        order: 3,
        name: "Ministre",
        description: "Signature du décret de nomination",
        durationHours: 24,
        allowDelegate: false,
        allowEscalate: false,
        requireComment: false,
        requireSign: true,
      },
    ],
  },
  {
    slug: "transfer-approval",
    name: "Approbation de Transfert de Personnel",
    description: "Circuit de validation des transferts d'agents entre directions ou ministères.",
    trigger: "EMPLOYEE_TRANSFERRED",
    stepDefinitions: [
      {
        order: 0,
        name: "Direction RH Source",
        description: "Initiation du transfert",
        durationHours: 48,
        allowDelegate: false,
        allowEscalate: false,
        requireComment: true,
        requireSign: false,
      },
      {
        order: 1,
        name: "Direction RH Destination",
        description: "Acceptation du transfert",
        durationHours: 48,
        allowDelegate: true,
        allowEscalate: false,
        requireComment: true,
        requireSign: false,
      },
      {
        order: 2,
        name: "Directeur Général",
        description: "Validation de la décision",
        durationHours: 24,
        allowDelegate: false,
        allowEscalate: true,
        requireComment: false,
        requireSign: false,
      },
      {
        order: 3,
        name: "Secrétaire Général",
        description: "Signature de l'acte de transfert",
        durationHours: 24,
        allowDelegate: false,
        allowEscalate: false,
        requireComment: false,
        requireSign: true,
      },
    ],
  },
  {
    slug: "procurement-approval",
    name: "Approbation des Marchés Publics",
    description: "Circuit de validation des contrats et marchés publics.",
    trigger: "CONTRACT_UPLOADED",
    stepDefinitions: [
      {
        order: 0,
        name: "Service Demandeur",
        description: "Expression du besoin",
        durationHours: 72,
        allowDelegate: false,
        allowEscalate: false,
        requireComment: true,
        requireSign: false,
      },
      {
        order: 1,
        name: "Cellule des Marchés",
        description: "Dossier d'appel d'offres",
        durationHours: 168,
        allowDelegate: true,
        allowEscalate: false,
        requireComment: true,
        requireSign: false,
      },
      {
        order: 2,
        name: "Contrôle Financier",
        description: "Disponibilité crédits",
        durationHours: 48,
        allowDelegate: false,
        allowEscalate: true,
        requireComment: true,
        requireSign: false,
      },
      {
        order: 3,
        name: "Secrétaire Général",
        description: "Autorisation de la dépense",
        durationHours: 48,
        allowDelegate: false,
        allowEscalate: false,
        requireComment: false,
        requireSign: true,
      },
      {
        order: 4,
        name: "Ministre",
        description: "Signature du contrat",
        durationHours: 72,
        allowDelegate: false,
        allowEscalate: false,
        requireComment: false,
        requireSign: true,
      },
    ],
  },
  {
    slug: "meeting-minutes-approval",
    name: "Approbation du Procès-Verbal de Réunion",
    description: "Validation et archivage des procès-verbaux de réunion officielle.",
    trigger: "DOCUMENT_CREATED",
    stepDefinitions: [
      {
        order: 0,
        name: "Rapporteur",
        description: "Rédaction du procès-verbal",
        durationHours: 24,
        allowDelegate: false,
        allowEscalate: false,
        requireComment: false,
        requireSign: false,
      },
      {
        order: 1,
        name: "Secrétaire de Séance",
        description: "Vérification des faits",
        durationHours: 24,
        allowDelegate: false,
        allowEscalate: false,
        requireComment: true,
        requireSign: false,
      },
      {
        order: 2,
        name: "Président de Séance",
        description: "Approbation et signature",
        durationHours: 24,
        allowDelegate: false,
        allowEscalate: false,
        requireComment: false,
        requireSign: true,
      },
    ],
  },
  {
    slug: "circular-approval",
    name: "Approbation de Circulaire Administrative",
    description: "Circuit de validation des circulaires et instructions administratives.",
    trigger: "DOCUMENT_PUBLISHED",
    stepDefinitions: [
      {
        order: 0,
        name: "Service Rédacteur",
        description: "Rédaction de la circulaire",
        durationHours: 48,
        allowDelegate: true,
        allowEscalate: false,
        requireComment: false,
        requireSign: false,
      },
      {
        order: 1,
        name: "Direction Juridique",
        description: "Conformité légale",
        durationHours: 48,
        allowDelegate: false,
        allowEscalate: true,
        requireComment: true,
        requireSign: false,
      },
      {
        order: 2,
        name: "Secrétaire Général",
        description: "Validation administrative",
        durationHours: 24,
        allowDelegate: false,
        allowEscalate: false,
        requireComment: false,
        requireSign: true,
      },
      {
        order: 3,
        name: "Ministre",
        description: "Signature et diffusion",
        durationHours: 24,
        allowDelegate: false,
        allowEscalate: false,
        requireComment: false,
        requireSign: true,
      },
    ],
  },
];
