/**
 * Client-side permission utilities.
 * Works with the permissions array stored in the NextAuth session.
 */

/** Returns true if the session's permission list contains the given permission. */
export function hasPermission(permissions: string[], permission: string): boolean {
  return permissions.includes(permission);
}

/** Returns true if the session has ALL of the given permissions. */
export function hasAllPermissions(permissions: string[], required: string[]): boolean {
  return required.every((p) => permissions.includes(p));
}

/** Returns true if the session has ANY of the given permissions. */
export function hasAnyPermission(permissions: string[], required: string[]): boolean {
  return required.some((p) => permissions.includes(p));
}

// ─── Well-known permission constants ─────────────────────────────────────────

export const PERMS = {
  MINISTRY_READ: "MINISTRY:READ",
  MINISTRY_CREATE: "MINISTRY:CREATE",
  MINISTRY_UPDATE: "MINISTRY:UPDATE",
  MINISTRY_DEACTIVATE: "MINISTRY:DEACTIVATE",

  DEPARTMENT_READ: "DEPARTMENT:READ",
  DEPARTMENT_CREATE: "DEPARTMENT:CREATE",
  DEPARTMENT_UPDATE: "DEPARTMENT:UPDATE",
  DEPARTMENT_DEACTIVATE: "DEPARTMENT:DEACTIVATE",

  DIVISION_READ: "DIVISION:READ",
  DIVISION_CREATE: "DIVISION:CREATE",
  DIVISION_UPDATE: "DIVISION:UPDATE",
  DIVISION_DEACTIVATE: "DIVISION:DEACTIVATE",

  PROVINCE_READ: "PROVINCE:READ",
  PROVINCE_CREATE: "PROVINCE:CREATE",
  PROVINCE_UPDATE: "PROVINCE:UPDATE",

  POSITION_READ: "POSITION:READ",
  POSITION_CREATE: "POSITION:CREATE",
  POSITION_UPDATE: "POSITION:UPDATE",

  ASSIGNMENT_READ: "EMPLOYEE_ASSIGNMENT:READ",
  ASSIGNMENT_CREATE: "EMPLOYEE_ASSIGNMENT:CREATE",
  ASSIGNMENT_UPDATE: "EMPLOYEE_ASSIGNMENT:UPDATE",

  USER_READ: "USER:READ",
  USER_CREATE: "USER:CREATE",
  USER_UPDATE: "USER:UPDATE",
  USER_DEACTIVATE: "USER:DEACTIVATE",

  ADMIN_VIEW_AUDIT_LOGS_ALL: "ADMIN:VIEW_AUDIT_LOGS_ALL",
  ADMIN_VIEW_AUDIT_LOGS_MINISTRY: "ADMIN:VIEW_AUDIT_LOGS_MINISTRY",
  AUTH_MANAGE_SESSIONS: "AUTH:MANAGE_SESSIONS",

  // ── Collaboration (v0.7.0) ────────────────────────────────────────────────
  CHANNEL_READ: "CHANNEL:READ",
  CHANNEL_CREATE: "CHANNEL:CREATE",
  CHANNEL_UPDATE: "CHANNEL:UPDATE",
  CHANNEL_ARCHIVE: "CHANNEL:ARCHIVE",
  CHANNEL_MANAGE_MEMBERS: "CHANNEL:MANAGE_MEMBERS",
  MESSAGE_SEND: "MESSAGE:SEND",
  MESSAGE_DELETE_ANY: "MESSAGE:DELETE_ANY",
  NOTIFICATION_READ: "NOTIFICATION:READ",

  // ── Documents (v0.8.0) ────────────────────────────────────────────────────
  DOCUMENT_READ: "DOCUMENT:READ",
  DOCUMENT_CREATE: "DOCUMENT:CREATE",
  DOCUMENT_UPDATE: "DOCUMENT:UPDATE",
  DOCUMENT_DELETE: "DOCUMENT:DELETE",
  DOCUMENT_SHARE: "DOCUMENT:SHARE",
  DOCUMENT_EXPORT: "DOCUMENT:EXPORT",
  DOCUMENT_PUBLISH: "DOCUMENT:PUBLISH",
  DOCUMENT_APPROVE: "DOCUMENT:APPROVE",
  DOCUMENT_MANAGE_TEMPLATES: "DOCUMENT:MANAGE_TEMPLATES",

  // ── Workflows & Approvals (v0.8.1) ────────────────────────────────────────
  WORKFLOW_READ: "WORKFLOW:READ",
  WORKFLOW_CREATE: "WORKFLOW:CREATE",
  WORKFLOW_UPDATE: "WORKFLOW:UPDATE",
  WORKFLOW_APPROVE: "WORKFLOW:APPROVE",
  WORKFLOW_CANCEL: "WORKFLOW:CANCEL",
  WORKFLOW_COMMENT: "WORKFLOW:COMMENT",
  WORKFLOW_MANAGE: "WORKFLOW:MANAGE",
  WORKFLOW_MANAGE_TEMPLATES: "WORKFLOW:MANAGE_TEMPLATES",
  TASK_READ: "TASK:READ",
  TASK_CREATE: "TASK:CREATE",
  TASK_UPDATE: "TASK:UPDATE",
  TASK_DELETE: "TASK:DELETE",
  TASK_COMMENT: "TASK:COMMENT",

  // ── Calendar & Meetings (v0.9.0) ──────────────────────────────────────────
  CALENDAR_READ: "CALENDAR:READ",
  CALENDAR_CREATE: "CALENDAR:CREATE",
  CALENDAR_UPDATE: "CALENDAR:UPDATE",
  CALENDAR_MANAGE: "CALENDAR:MANAGE",
  MEETING_READ: "MEETING:READ",
  MEETING_CREATE: "MEETING:CREATE",
  MEETING_UPDATE: "MEETING:UPDATE",
  MEETING_MANAGE: "MEETING:MANAGE",

  // ── Executive Office (v1.0.0) ─────────────────────────────────────────────
  EXECUTIVE_READ: "EXECUTIVE:READ",
  EXECUTIVE_OFFICE_READ: "EXECUTIVE_OFFICE:READ",
  EXECUTIVE_OFFICE_CREATE: "EXECUTIVE_OFFICE:CREATE",
  EXECUTIVE_OFFICE_UPDATE: "EXECUTIVE_OFFICE:UPDATE",
  EXECUTIVE_OFFICE_MANAGE: "EXECUTIVE_OFFICE:MANAGE",
  CABINET_READ: "CABINET:READ",
  CABINET_CREATE: "CABINET:CREATE",
  CABINET_UPDATE: "CABINET:UPDATE",
  CABINET_MANAGE: "CABINET:MANAGE",
  CABINET_DECISION_READ: "CABINET_DECISION:READ",
  CABINET_DECISION_CREATE: "CABINET_DECISION:CREATE",
  CABINET_DECISION_ADOPT: "CABINET_DECISION:ADOPT",
  BRIEFING_READ: "BRIEFING:READ",
  BRIEFING_CREATE: "BRIEFING:CREATE",
  BRIEFING_UPDATE: "BRIEFING:UPDATE",
  BRIEFING_APPROVE: "BRIEFING:APPROVE",
  CORRESPONDENCE_READ: "CORRESPONDENCE:READ",
  CORRESPONDENCE_CREATE: "CORRESPONDENCE:CREATE",
  CORRESPONDENCE_UPDATE: "CORRESPONDENCE:UPDATE",
  EXECUTIVE_ANNOUNCEMENT_CREATE: "EXECUTIVE_ANNOUNCEMENT:CREATE",
  EXECUTIVE_ANNOUNCEMENT_PUBLISH: "EXECUTIVE_ANNOUNCEMENT:PUBLISH",
  KPI_READ: "KPI:READ",
  KPI_MANAGE: "KPI:MANAGE",

  // ── Organizations (v1.0.2) ────────────────────────────────────────────────
  ORGANIZATION_READ: "ORGANIZATION:READ",
  ORGANIZATION_CREATE: "ORGANIZATION:CREATE",
  ORGANIZATION_UPDATE: "ORGANIZATION:UPDATE",
  ORGANIZATION_DELETE: "ORGANIZATION:DELETE",
} as const;
